config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    resources :items, only: [:index,:show]
    resource :customers, only: [:edit,:update]
    get '/customers/my_page', to: 'customers#show', as: 'my_page'
    get 'customers/confirm'
    patch 'customers/deactivate'
    delete 'carts/destroy_all', to: 'carts#destroy_all', as: 'carts_destroy_all'
    resources :carts, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:update,:destroy]
    resources :destinations, except: [:show,:new]
    resources :genres, only: [:show]
  end

    # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:show,:destroy]
    get 'customers/:id/order_history', to: 'customers#order_history', as: 'customers_order_history'
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end

  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

    belongs_to :genre
    has_many :order_items
    has_many :carts

    has_one_attached :image

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price_without_tax, presence: true
    validates :is_stopped, inclusion: {in: [true, false]}
    validates :image, presence: true

    def price_with_tax
      tax = 1 + 0.10
      ( self.price_without_tax * tax).floor
    end


    def get_image(width, height)
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
        image.variant(resize_to_limit: [width, height]).processed
    end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item_new = Item.new
    @genres = Genre.all
  end

  def create
    @item_new = Item.new(item_params)
    if @item_new.save
      redirect_to admin_item_path(@item_new), notice: "商品が登録されました。"
    else
      @genres = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "変更内容が保存されました。"
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price_without_tax, :is_stopped)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>商品編集</h2>
      </div>

      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @item %>
        <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
          <div class="field d-flex mb-3">
            <%= f.label :image, "商品画像", class: "w-25" %><br>
            <%= f.file_field :image, accept: 'image/*', class: "form-control-file w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :name, "商品名", class: "w-25" %><br>
            <%= f.text_field :name, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :introduction, "商品説明", class: "w-25" %><br>
            <%= f.text_area :introduction, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :genre_id, "ジャンル", class: "w-25" %><br>
            <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい", class: "form-select w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :price_without_tax, "税抜価格", class: "w-25" %><br>
            <%= f.number_field :price_without_tax, class: "w-50" %>円
          </div>

          <div class="field d-flex mb-3">
            <p class="w-25">販売ステータス</p>
            <div class="is_stopped">
              <%= f.radio_button :is_stopped, false %>
              <%= f.label :is_stopped, "販売中", value: false %>

              <%= f.radio_button :is_stopped, true, class: "ml-3"%>
              <%= f.label :is_stopped, "販売停止中", value: true %>
            </div>
          </div>

          <div class="actions text-center">
            <%= f.submit "変更を保存", class: 'btn btn-success w-50' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>商品一覧</h2>
        <div class="text-right">
          <%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-primary" %>
        </div>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item) %></td>
              <td><%= item.price_without_tax.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_stopped == false %>
                <td class="text-success">販売中</td>
              <% else %>
                <td class="text-black-50">販売停止中</td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>

        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>商品新規登録</h2>
      </div>

      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @item_new %>
        <%= form_with model: @item_new, url: admin_items_path, local: true do |f| %>
          <div class="field d-flex mb-3">
            <%= f.label :image, "商品画像", class: "w-25" %><br>
            <%= f.file_field :image, accept: 'image/*', class: "form-control-file w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :name, "商品名", class: "w-25" %><br>
            <%= f.text_field :name, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :introduction, "商品説明", class: "w-25" %><br>
            <%= f.text_area :introduction, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :genre_id, "ジャンル", class: "w-25" %><br>
            <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい", class: "form-select w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :price_without_tax, "税抜価格", class: "w-25" %><br>
            <%= f.number_field :price_without_tax, class: "w-50" %>円
          </div>

          <div class="field d-flex mb-3">
            <p class="w-25">販売ステータス</p>
            <div class="is_stopped">
              <%= f.radio_button :is_stopped, false %>
              <%= f.label :is_stopped, "販売中", value: false %>

              <%= f.radio_button :is_stopped, true, class: "ml-3"%>
              <%= f.label :is_stopped, "販売停止中", value: true %>
            </div>
          </div>

          <div class="actions text-center">
            <%= f.submit "新規登録", class: 'btn btn-success w-50' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>商品詳細</h2>
      </div>

      <div class="row pb-3">
        <div class="col-md-3">
          <%= image_tag @item.get_image(200, 150), class: "w-100" %>
        </div>

        <div class="col-md-7">
          <table class="table table-borderless">
            <tr>
              <th>商品名</th>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <th>税込価格<br>(税抜価格)</th>
              <td>
                <%= @item.price_with_tax.to_s(:delimited) %>
                (<%= @item.price_without_tax.to_s(:delimited) %>)円
              </td>
            </tr>
            <tr>
              <th nowrap>販売ステータス</th>
              <% if @item.is_stopped == false %>
                <td class="text-success">販売中</td>
              <% else %>
                <td class="text-black-50">販売停止中</td>
              <% end %>
            </tr>
          </table>

          <div class="text-center">
            <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success w-50" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>