config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    resources :items, only: [:index,:show]
    resource :customers, only: [:edit,:update]
    get '/customers/my_page', to: 'customers#show', as: 'my_page'
    get 'customers/confirm'
    patch 'customers/deactivate'
    delete 'carts/destroy_all', to: 'carts#destroy_all', as: 'carts_destroy_all'
    resources :carts, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:update,:destroy]
    resources :destinations, except: [:show,:new]
    resources :genres, only: [:show]
  end

    # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:show,:destroy]
    get 'customers/:id/order_history', to: 'customers#order_history', as: 'customers_order_history'
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end

  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts
  has_many :orders
  has_many :destinations

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true,
    numericality: { only_integer: true}, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true,
    numericality: { only_integer: true}

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @customer_name = @customer.last_name + " " + @customer.first_name
    @customer_kana = @customer.last_name_kana + " " + @customer.first_name_kana

  end

  def edit
    @customer = Customer.find(params[:id])
    @customer_name = @customer.last_name + " " + @customer.first_name
  end

  def update
    @customer = Customer.find(params[:id])
    @customer_name = @customer.last_name + " " + @customer.first_name
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = "編集した内容を保存しました。"
    else
      render :edit
    end
  end

  def order_history
    @customer = Customer.find(params[:id])
    @customer_name = @customer.last_name + " " + @customer.first_name
    @orders = @customer.orders.order(id: "DESC").page(params[:page]).per(10)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2><%= @customer_name %>さんの会員情報編集</h2>
      </div>

      <div class="row-md-10 pb-3">

        <%= render 'layouts/errors', obj: @customer %>
        <table class="table">
          <tr>
            <th>
              会員ID
            </th>
            <th>
              <%= @customer.id %>
            </th>
          </tr>
          <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true, method: :patch do |form| %>
          <tr>
            <th>
              氏名
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name_kana, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name_kana, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              郵便番号
            </th>
            <th>
              <%= form.text_field :postal_code, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              住所
            </th>
            <th>
              <%= form.text_field :address, class: "form-control w-75 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= form.text_field :telephone_number, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              メールアドレス
            </th>
            <th>
              <%= form.text_field :email, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <%= form.radio_button :is_deleted, :false %>有効
              <%= form.radio_button :is_deleted, :true %>退会
            </th>
          </tr>
          <tr>
            <th>

            </th>
            <th>
              <%= form.submit "変更を保存", class: "btn btn-success w-25" %>
            </th>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>会員一覧</h2>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>
                会員ID
              </th>
              <th>
                氏名
              </th>
              <th>
                メールアドレス
              </th>
              <th>
                ステータス
              </th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <th>
                <%= customer.id %>
              </th>
              <th>
                <%= link_to admin_customer_path(customer.id), method: :get do %>
                  <%= customer.last_name + customer.first_name %>
                <% end %>
              </th>
              <th>
                <%= customer.email %>
              </th>
              <th>
                <% if customer.is_deleted == false %>
                  有効
                <% else %>
                  退会
                <% end %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
      	<div>
          <p><%= paginate @customers %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/order_history.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="row-md-10 pb-3">
        <h2><%= @customer_name %>さんの注文履歴</h2>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>
                購入日時
              </th>
              <th>
                注文個数
              </th>
              <th>
                注文ステータス
              </th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
              <th>
                <%= link_to admin_order_path(order.id) do %>
                  <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                <% end %>
              </th>
              <th>
                <%= order.order_items.sum(:amount) %>
              </th>
              <th>
                <%= order.order_status_i18n %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
      	<div>
          <p><%= paginate @orders %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="row-md-10 pb-3">
        <h2><%= @customer_name %>さんの会員詳細</h2>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <tr>
            <th>
              会員ID
            </th>
            <th>
              <%= @customer.id %>
            </th>
          </tr>
          <tr>
            <th>
              氏名
            </th>
            <th>
              <%= @customer_name %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th>
              <%= @customer_kana %>
            </th>
          </tr>
          <tr>
            <th>
              郵便番号
            </th>
            <th>
              <%= @customer.postal_code %>
            </th>
          </tr>
          <tr>
            <th>
              住所
            </th>
            <th>
              <%= @customer.address %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= @customer.telephone_number %>
            </th>
          </tr>
          <tr>
            <th>
              メールアドレス
            </th>
            <th>
              <%= @customer.email %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <% if @customer.is_deleted == false %>
                有効
              <% else %>
                退会
              <% end %>
            </th>
          </tr>
          <tr>
            <th>

            </th>
            <th>
              <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success", method: :get %>
              <%= link_to "注文履歴一覧を見る", admin_customers_order_history_path(@customer.id), class: "btn btn-primary", method: :get %>
            </th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>