config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    resources :items, only: [:index,:show]
    resource :customers, only: [:edit,:update]
    get '/customers/my_page', to: 'customers#show', as: 'my_page'
    get 'customers/confirm'
    patch 'customers/deactivate'
    delete 'carts/destroy_all', to: 'carts#destroy_all', as: 'carts_destroy_all'
    resources :carts, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:update,:destroy]
    resources :destinations, except: [:show,:new]
    resources :genres, only: [:show]
  end

    # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:show,:destroy]
    get 'customers/:id/order_history', to: 'customers#order_history', as: 'customers_order_history'
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end

  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true

    has_many :items

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre_new = Genre.new
  end

  def create
    @genre_new = Genre.new(genre_params)
    if @genre_new.save
      redirect_to admin_genres_path
      flash[:notice] = "ジャンル名を追加しました。"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice] = "編集した内容を保存しました。"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10">

      <div class="row-md-10 pb-3">
        <h2>ジャンル編集</h2>
      </div>

      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @genre %>
        <%= form_with model: @genre, url: admin_genre_path, local: true, method: :patch do |form| %>
          <div class="d-flex mb-3">
            <%= form.label :name, "ジャンル名", class: "mr-3" %>
            <%= form.text_field :name, class: "form-control w-25 mr-3" %>
            <%= form.submit "変更を保存", class: "btn btn-success w-25 mr-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>ジャンル一覧・追加</h2>
      </div>

      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @genre_new %>
        <%= form_with model: @genre_new, url: admin_genres_path, local: true, method: :post do |form| %>
          <div class="d-flex mb-3">
            <%= form.label :name, "ジャンル名", class: "mr-3" %>
            <%= form.text_field :name, class: "form-control w-25 mr-3" %>
            <%= form.submit "新規登録", class: "btn btn-success w-25 mr-3" %>
          </div>
        <% end %>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>
                ジャンル
              </th>
              <th>

              </th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <th>
                <%= genre.name %>
              </th>
              <th>
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success w-50", method: :get %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>