config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    resources :items, only: [:index,:show]
    resource :customers, only: [:edit,:update]
    get '/customers/my_page', to: 'customers#show', as: 'my_page'
    get 'customers/confirm'
    patch 'customers/deactivate'
    delete 'carts/destroy_all', to: 'carts#destroy_all', as: 'carts_destroy_all'
    resources :carts, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:update,:destroy]
    resources :destinations, except: [:show,:new]
    resources :genres, only: [:show]
  end

    # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:show,:destroy]
    get 'customers/:id/order_history', to: 'customers#order_history', as: 'customers_order_history'
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end

  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :customer
    belongs_to :item

    def subtotal
      item.price_with_tax * amount
    end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts
  has_many :orders
  has_many :destinations

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true,
    numericality: { only_integer: true}, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true,
    numericality: { only_integer: true}

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/destination.rb
class Destination < ApplicationRecord

    belongs_to :customer

    validates :postal_code, presence: true,
      numericality: { only_integer: true}, length: { is: 7 }
    validates :address, presence: true
    validates :name, presence: true

    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true

    has_many :items

end

app/models/item.rb
class Item < ApplicationRecord

    belongs_to :genre
    has_many :order_items
    has_many :carts

    has_one_attached :image

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price_without_tax, presence: true
    validates :is_stopped, inclusion: {in: [true, false]}
    validates :image, presence: true

    def price_with_tax
      tax = 1 + 0.10
      ( self.price_without_tax * tax).floor
    end


    def get_image(width, height)
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
        image.variant(resize_to_limit: [width, height]).processed
    end


end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_items

    has_many :items, through: :order_items

    validates :postal_code, presence: true,
      numericality: { only_integer: true}, length: { is: 7 }
    validates :address, presence: true
    validates :name, presence: true
    validates :postage, presence: true
    validates :total_payment, presence: true
    validates :payment_method, presence: true

    enum payment_method: { credit_card: 0, bank_transfer: 1 }
    enum order_status: { waiting: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

    belongs_to :order
    belongs_to :item

    enum making_status: { unable: 0, waiting: 1, making: 2, finish: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre_new = Genre.new
  end

  def create
    @genre_new = Genre.new(genre_params)
    if @genre_new.save
      redirect_to admin_genres_path
      flash[:notice] = "ジャンル名を追加しました。"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice] = "編集した内容を保存しました。"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.order(id: "DESC").page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item_new = Item.new
    @genres = Genre.all
  end

  def create
    @item_new = Item.new(item_params)
    if @item_new.save
      redirect_to admin_item_path(@item_new), notice: "商品が登録されました。"
    else
      @genres = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "変更内容が保存されました。"
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price_without_tax, :is_stopped)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_root_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customers
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
   end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row mx-auto">
    <div id="error_explanation">
      <h3 class="text-danger"><%= obj.errors.count %> 件のエラーが発生しました</h3>
      <ul class="text-danger">
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='w-auto border-top bg-secondary'>
  <div class='container'>
  	<div class='row pt-3'>
    	<div class='mx-auto'>
    		<p class="text-white">© Nagano Cake</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom">
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container">
      <% if admin_signed_in? %>
      <a class="navbar-brand" href="/admin"><span>Nagano Cake</span></a>
      <% else %>
      <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>
      <% end %>
      <% if customer_signed_in? %>
      <span class="navbar-text">ようこそ<%= current_customer.last_name %>さん</span>
      <% end %>
      <% if admin_signed_in? %>
      <span class="navbar-text">管理者：<%= current_admin.last_name %>さん</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
          <li>
            <%= link_to "マイページ", my_page_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "カート", carts_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to "商品一覧", admin_items_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "会員一覧", admin_customers_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li>
            <%= link_to "About", about_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "ログイン", new_customer_session_path, class: 'nav-link' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="w-auto bg-success">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-3">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:notice] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="w-auto bg-danger">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-3">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:alert] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<table class="table border">
  <thead class="table-dark">
    <tr>
      <th>
        ジャンル検索
      <th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>
        <ul class="list-group list-group-flush">
          <% genres.each do |f| %>
            <% if f.items.count != 0 %>
            <li class="list-group-item">
              <%= link_to f.name, genre_path(f) %>
            </li>
            <% end %>
          <% end %>
        </ul>
      <th>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CakeEcApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/notice' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>